{
 "title": "Delayed Jobs Graphs",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Delayed Jobs Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "delayed_jobs_total_count", "legendFormat": "Delayed Jobs Total" }
   ]
  },
  {
   "title": "Pending Delayed Jobs Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delayed_jobs_pending_total_count",
     "legendFormat": "Pending Delayed Jobs Total"
    }
   ]
  },
  {
   "title": "Delayed Jobs by queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delayed_jobs_queue_total_count) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Delayed Jobs by priority",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delayed_jobs_queue_total_count) by (priority)",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "Delayed Jobs by attempts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delayed_jobs_queue_total_count) by (attempts)",
     "legendFormat": "{{attempts}}"
    }
   ]
  },
  {
   "title": "Delayed Jobs with errors by queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delayed_jobs_queue_error_total_count) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Jobs to be executed Today",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delayed_jobs_to_be_executed_today_count) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Pending Jobs by Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delayed_jobs_queue_pending_total_count) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Failed Jobs today by queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delayed_jobs_failed_today_count) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Delayed Jobs by handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delayed_jobs_handler_count) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Performable Delayed Jobs By Method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delayed_jobs_performable_count) by (method_name)",
     "legendFormat": "{{method_name}}"
    }
   ]
  },
  {
   "title": "Performable Delayed Jobs By Class",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delayed_jobs_performable_count) by (object)",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Failed Performable Delayed Jobs by class",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delayed_jobs_performable_failed_count) by (object)",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Failed Delayed Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delayed_jobs_queue_failed_total_count) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  }
 ]
}