{
 "title": "Delayed Job counts",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Delayed Jobs",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    { "expr": "delayed_jobs_total_count" }
   ]
  },
  {
   "title": "Total  Pending Delayed Jobs",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "delayed_jobs_pending_total_count"
    }
   ]
  },
  {
   "title": "Total Delayed Jobs",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delayed_jobs_queue_total_count) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Total  Pending Delayed Jobs by queue",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delayed_jobs_queue_pending_total_count) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Total  Delayed Jobs with errors by queue",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delayed_jobs_queue_error_total_count) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Total  Failed Delayed Jobs by queue",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delayed_jobs_queue_failed_total_count) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Total  Delayed Jobs to be executed today by queue",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delayed_jobs_to_be_executed_today_count) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Total  Delayed Jobs by handler ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delayed_jobs_handler_error_count) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Total  Performable Delayed Jobs by method ",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delayed_jobs_performable_count) by (method_name)",
     "legendFormat": "{{method_name}}"
    }
   ]
  }
 ]
}